spring.application.name=SANVEX Technologies
server.port=8080
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.datasource.url=jdbc:mysql://localhost:3306/sanvex
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update