spring.application.name=SANVEX Technologies
server.port=8080
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.datasource.url=${jdbc:postgresql://dpg-d98kedl7vvec739prvb0-a:5432/sanvex_db}
spring.datasource.username=${sanvex_db_user}
spring.datasource.password=${e6EZw9OpOZ8TdoH2JksyTQNj3zntkpEO}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update